### ISSUE TITLE
bad zip file generated for large-ish archives

### ISSUE THREAD

**Issue by mikepschneider** [fringd/zipline#24]
Hello,
When I use zipline to download an archive with about 550MB  (about 125 image files) the zipfile fails.  It doesn't  download the entire file, sometimes its 480MB, sometimes it's 505MB, etc. but consistently it doesn't work.

When I try to unzip it it says this: 
$ unzip test.zip
Archive:  test.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of test.zip or
        test.zip.zip, and cannot find test.zip.ZIP, period.

Is there an upper limit to the # of files or file size zipline can handle?  There are no obvious errors on the server.  Any suggestions to debug or fix?   Thanks.

**Comment by fringd** [comment]
Is it possible that the server is not configured to stream properly and it
is running out of memory? What server are you using?

**Comment by mikepschneider** [comment]
The server is heroku.  That's my best guess that it's running out of memory but there aren't any visible errors in the log.

**Comment by mikepschneider** [comment]
Actually it appears to be a timeout on heroku.  I can increase the timeout and it will take longer to fail, but there is always a bigger file to download over a slower link, so increasing the timeout will eventually fail.  I guess there is not much else to be done about it for a streaming solution like this.

**Comment by julik** [comment]
Heroku docs here https://devcenter.heroku.com/articles/limits specify that you can keep the socket open for longer but you need to be writing to the socket every 55 seconds or less. From my experience with Rubyzip, if you use deflate compression the actual writing to the output will happen at the very end of the data for the compressed file since Rubyzip never flushes the deflater (and never does intermediate flushes). Running out of memory is also a possibility because if you keep a Deflater open for long enough it will buffer compressed data in memory until you flush it. So this has more to do with the way Rubyzip handles it than anything else. One of the reasons we bypassed Rubyzip entirely in our library.

**Comment by mikepschneider** [comment]
It seems to be writing to the file continuously (the filesize is constantly growing in the partially downlloaded file in the browser).  The timeout is coming from unicorn (ruby http server) - when I change the timeout in the unicorn config to 30 or 120 I see the error happen exactly at that time.

**Comment by julik** [comment]
AFAIK Unicorn has hard timeouts even if you keep writing to the socket - we use Puma for those streaming workloads instead, or you could try Rainbows...
